Update/2303
mozilla-services/skeleton pull request #10
Opened 2023-03-23 00:30 UTC by jrconlin

## Description

Update libraries and calls for 2023 (add comments, required features, etc.)

## Testing

Well, there's one test at least.

2023-04-17 20:02 UTC, pjenvey submitted a review, later dismissed

2023-04-17 20:02 UTC, pjenvey commented on Dockerfile
> +FROM rust:1.68 as builder
Apparently `rust:1.68` is now based on `bullseye`. Let's specify the same debian release in both the builder and the final image so they don't go out of sync.

```suggestion
FROM rust:1.68-bullseye as builder
```
(or `buster`)

2023-04-17 20:02 UTC, pjenvey commented on Dockerfile
> +FROM debian:buster-slim
(or keep `buster`)
```suggestion
FROM debian:bullseye-slim
```

2023-04-17 20:02 UTC, pjenvey commented on src/server/mod.rs
> +mod dockerflow;
Forgot to git add `dockerflow.rs`

2023-04-17 20:02 UTC, pjenvey commented on src/server/mod.rs
> +                web::resource("/__lbheartbeat__")
Let's use `configure` for all the dockerflow endpoints here (see [merino for an example](https://github.com/mozilla-services/merino/blob/main/merino-web/src/lib.rs#L140))

2023-04-17 20:02 UTC, pjenvey commented on src/server/mod.rs
> +            .service(web::resource("/__status__").route(web::get().to(dockerflow::status_route)))
Should probably kill the non dockerflow `__status__` as we already have `__heartbeat__` and `__version__`, doesn't it come from autopush's specific `/status`?

2023-04-18 15:12 UTC, jrconlin commented on Dockerfile
> +FROM rust:1.68 as builder
Going with Buster for now.

2023-04-18 23:27 UTC, pjenvey requested changes

2023-04-18 23:27 UTC, pjenvey commented on src/web/mod.rs
> +    "/__status__",
```suggestion
```

2023-10-23 17:58 UTC, pjenvey approved these changes

2023-10-23 23:29 UTC, merged